# Generated by Django 2.2 on 2019-04-18 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.TextField()),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=2)),
                ('product_state', models.TextField()),
            ],
        ),
    ]
