# Generated by Django 2.2 on 2019-04-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190418_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_state',
            field=models.BooleanField(),
        ),
    ]
