# Generated by Django 2.2 on 2019-04-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190418_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_state',
            field=models.BooleanField(default=True),
        ),
    ]
