# Generated by Django 2.2 on 2019-04-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190418_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_quantity',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('Coffee', 'Coffee'), ('Tea', 'Tea'), ('Cake', 'Cake'), ('Sandwiches', 'Sandwiches')], default='Coffee', max_length=255),
        ),
    ]
