# Generated by Django 2.2 on 2019-04-18 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190418_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('ingredient_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('Coffee bean', 'Coffee bean'), ('Full Cream Milk', 'Full Cream Milk'), ('White Bread', 'White Bread'), ('Black Tea', 'Black Tea')], max_length=255)),
                ('quantity', models.IntegerField(default=10)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='product_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
