# Generated by Django 2.2 on 2019-04-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20190418_1136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='order_num',
            new_name='display_no',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='product_id',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='name',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(default='N', max_length=255),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='input_name',
            field=models.CharField(default='Add New Ingredient Here', max_length=255),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order_status',
            field=models.BooleanField(default=True),
        ),
    ]
