# Generated by Django 2.2 on 2019-04-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20190418_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order_status',
            field=models.CharField(choices=[('Preparing', 'Preparing'), ('Done', 'Done')], max_length=255),
        ),
    ]
