# Generated by Django 2.2 on 2019-05-22 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('brief_content', models.TextField()),
                ('content', models.TextField()),
                ('publish_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('ingredient_id', models.AutoField(primary_key=True, serialize=False)),
                ('input_name', models.CharField(default='Add New Ingredient Here', max_length=255)),
                ('quantity', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_item_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('order_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(default='N', max_length=255)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('order_status', models.CharField(choices=[('Preparing', 'Preparing'), ('Done', 'Done')], max_length=255)),
                ('order_number', models.IntegerField(default=1)),
                ('order_sub_total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('user_name', models.CharField(default='N', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Paymentstatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentstatus', models.BooleanField(default=False)),
                ('ordercontent', models.CharField(default='N', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('product_state', models.BooleanField(default=True)),
                ('product_size', models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], max_length=255)),
                ('product_type', models.CharField(choices=[('Coffee', 'Coffee'), ('Tea', 'Tea'), ('Cake', 'Cake'), ('Sandwiches', 'Sandwiches')], default='Coffee', max_length=255)),
                ('product_quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('staff_username', models.CharField(max_length=100)),
                ('staff_password', models.CharField(max_length=100)),
                ('staff_email', models.EmailField(blank=True, max_length=70, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
