# Generated by Django 2.2 on 2019-04-20 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='staff',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='password',
            new_name='staff_password',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='username',
            new_name='staff_username',
        ),
    ]
