# Generated by Django 2.2 on 2019-04-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0002_auto_20190420_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='staff_email',
            field=models.EmailField(blank=True, max_length=70, null=True, unique=True),
        ),
    ]
