# Generated by Django 2.2 on 2019-04-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0003_staff_staff_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
