# Generated by Django 2.2 on 2019-04-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0004_staff_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_email',
            field=models.EmailField(blank=True, max_length=70, null=True),
        ),
    ]
